### ISSUE TITLE
The calculated peak frequency is half the actual signal frequency

### ISSUE THREAD

**Issue by JuriShalkin** [tobozo/ESP32-Audio-Spectrum-Waveform-Display#1]
Hello! It seems to me that reading data from the ADC does not work correctly: the reading frequency does not match the declared sampling frequency. I use an audio signal to evaluate the correct operation and get a peak frequency half that of the actual signal frequency. I took the initial ADC data from the array vReal and did the Fourier transform in the MS Excel and got the same result.

**Comment by tobozo** [comment]
Hello and thanks for your feedback.

Do you mean the [captureSoundSample()](https://github.com/tobozo/ESP32-Audio-Spectrum-Waveform-Display/blob/wrover-kit/ESP32_Spectrum_Display_03.ino#L295) code would need revision or could it be a clumsy adc setting in the [setup()](https://github.com/tobozo/ESP32-Audio-Spectrum-Waveform-Display/blob/wrover-kit/ESP32_Spectrum_Display_03.ino#L481) causing that?

**Comment by JuriShalkin** [comment]
Sorry, this is my mistake. I did not use your code, but this code https://github.com/G6EJD/ESP32-8266-Audio-Spectrum-Display

**Comment by tobozo** [comment]
@JuriShalkin have you tried this one? it uses separate tasks for analogRead and TFT rendering

https://github.com/CelliesProjects/M5visualisation_2core
